# Generated by Django 4.0.5 on 2022-06-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socnet', '0006_profile_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friend_of', to='socnet.profile'),
        ),
    ]
