# Generated by Django 4.0.5 on 2022-06-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socnet', '0008_remove_profile_birth_date_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='My bio', max_length=300),
        ),
    ]
