# Generated by Django 4.0.5 on 2022-06-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socnet', '0009_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default.jpg', height_field=92, upload_to='static/images', width_field=92),
        ),
    ]
